language: python
python:
  - "2.7"
install: pip install .
script:
  - git --version
  - hg --version --quiet
  - svn --version --quiet
  - export TEST_LOG_FILE=`mktemp`; python tests.py || (cat $TEST_LOG_FILE; false)
