language: python
python:
  - "2.5"
  - "2.6"
  - "2.7"
install:
  - pip install .
  - pip install simplejson
before_script:
  - git --version
  - hg --version --quiet
  - svn --version --quiet
script:
  - export TEST_LOG_FILE=`mktemp`; python tests.py -v || (cat $TEST_LOG_FILE; false)
