language: python
env:
  global:
    - SUITE=
  matrix:
    - TOXENV=py26
    - TOXENV=py27
    - TOXENV=py32
    - TOXENV=py33
install:
  - pip install tox
before_script:
  - git --version
  - hg --version --quiet
  - svn --version --quiet
  - python --version
script:
  - |
    export TEST_LOG_FILE=`mktemp`
    tox -v -- -v --cov anyvcs $SUITE || (cat $TEST_LOG_FILE; false)
