language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
install:
  - pip install .
  - sh ./.travis-requirements.sh
before_script:
  - git --version
  - hg --version --quiet
  - svn --version --quiet
script:
  - sh ./.travis-script.sh
