language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
install:
  - pip install .
  - "if [ `python3 --version 2>&1 | cut -f2 -d' ' | cut -f1 -d.` -lt 3 ]; then pip install unittest2; fi"
before_script:
  - git --version
  - hg --version --quiet
  - svn --version --quiet
script:
  - export TEST_LOG_FILE=`mktemp`; python tests.py -v || (cat $TEST_LOG_FILE; false)
